- hosts: web
  vars_files:
       - "{{ ansible_facts ['distribution'] }}-{{ ansible_facts['distribution_major_version'] }}.yml"
  
  tasks:
  - name: "Install web server"
    package:
            name: "{{ package_name }}"
            state: present

  - name: "copy webpage"
    template:
            src: web.html.j2
            dest: "{{ doc_root }}"
    notify: 
    - restart apache service


  - name: "Start the service"
    service:
      name: "{{ service_name }}"
      state: started

  handlers:
  - name: "restart apache service"
    service:
            name: "{{ service_name }}"
            state: restarted



